stages:
  - test # Launching the flutter tests
  - build # Trying to build the app

flutter_test:
  stage: test
  script:
    - flutter test
  tags:
    - gitlab-ce-runner-1

flutter_build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - gitlab-ce-runner-1