# Docker container with flutter installed to run on Univ-Lille's servers
image: cirrusci/flutter

stages:
  - test # Launching the flutter tests
  - build # Trying to build the app

flutter_test:
  stage: test
  script:
    - flutter test

flutter_build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
    - flutter pub run flutter_launcher_icons
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk